spring.application.name=gateaway-service
server.port=8080

backend.service.url=${BACKEND_SERVICE_URL:http://localhost:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gateway_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret=${JWT_SECRET:myverysecuresecretkeymyverysecuresecretkey}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
admin.refresh-token.expiration-ms=${ADMIN_REFRESH_TOKEN_EXPIRATION_MS:604800000}
#spring.cloud.gateway.server.webmvc.routes[0].id=backend-service-route
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/**
